<?php

namespace app\v1\lcic\controller;

class dp extends user
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function user()
    {

    }

    public function room()
    {

    }
}