<?php

namespace app\v1\rcon\controller;

use app\v1\image\controller\create;
use app\v1\rcon\model\RconModel;
use Ret;

class index extends create
{

    public mixed $rcon;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->rcon = RconModel::where('project', $this->token)->find();
        if (!$this->rcon) {
            Ret::Fail(404, null, '未找到项目');
        }
    }

    public function test()
    {

    }
}