<?php

namespace app\v1\rcon\controller;

use Ret;

class palworld extends rcon
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function ping()
    {
        Ret::Success(0, trim($this->conn->Rcon('Ping')));
    }
}