<?php

namespace app\v1\rcon\controller;

class palworld extends rcon
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function ping()
    {
        $this->ping();
    }
}