<?php

namespace app\v1\nlp\controller;


use AlibabaCloud\SDK\Alinlp\V20200629\Alinlp;
use AlibabaCloud\SDK\Alinlp\V20200629\Models\GetNerChEcomRequest;
use AlibabaCloud\Tea\Exception\TeaUnableRetryError;
use app\v1\image\controller\create;
use app\v1\nlp\model\NlpAliyunModel;
use app\v1\nlp\model\NlpModel;
use Darabonba\OpenApi\Models\Config;

class index extends create
{

    protected $nlp_proc = [];

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $project = NlpModel::where("project", $this->token)->findOrEmpty();
        if (empty($project)) {
            \Ret::Fail(404, null, "项目不存在");
        } else {
            $this->nlp_proc = $project->toArray();
        }
        switch ($this->nlp_proc["type"]) {
            case "aliyun":
                $this->aliyun();
                break;
        }
    }

    public function aliyun()
    {
        $ali = NlpAliyunModel::where('tag', $this->nlp_proc['tag'])->find();

        $config = new Config();
        $config->accessKeyId = $ali["accessKeyId"];
        $config->accessKeySecret = $ali["accessKeySecret"];
        $config->regionId = $ali["regionId"];
        $config->endpoint = $ali["endpoint"];
        $client = new Alinlp($config);
        $request = new GetNerChEcomRequest();
        $request->serviceCode = 'alinlp';
        $request->text = '服务很好';

        try {
            $response = $client->getNerChEcom($request);
            $json_string = json_encode($response->body, JSON_UNESCAPED_UNICODE);
            echo $json_string;
        } catch (TeaUnableRetryError $e) {
            var_dump($e->getMessage());
            var_dump($e->getErrorInfo());
            var_dump($e->getLastException());
            var_dump($e->getLastRequest());
        }
    }
}