<?php

namespace app\v1\wechat\controller;

use app\v1\wechat\model\WechatUserModel;
use Input;
use Ret;
use Wechat\KefuMessage;

class message extends offiaccount
{

    protected string|null $openid = null;

    public function initialize()
    {
        if (request()->get("token")) {
            parent::initialize(); // TODO: Change the autogenerated stub
            $this->openid = Input::Post('openid');
        } else {
            $this->openid = Input::Post('openid');
            $wechat_user = WechatUserModel::where('openid', $this->openid)->find();
            if (!$wechat_user) {
                Ret::Fail(406, null, '用户还未关注或还未向公众号发过消息');
            }
            $this->token = $wechat_user["project"];
            parent::initialize(); // TODO: Change the autogenerated stub
        }
    }

    public function text()
    {
        $content = Input::Post('content');
        $kefu = new KefuMessage($this->access_token, $this->openid);
        $kefu->text($content);
        $ret = $kefu->send();
        if ($ret->isSuccess()) {
            Ret::Success(0, $ret->response, $ret->getError());
        } else {
            Ret::Fail(200, $ret->response, $ret->getError());
        }
    }
}