<?php

namespace app\v1\qwen\controller;


use AlibabaCloud\SDK\Alinlp\V20200629\Alinlp;
use AlibabaCloud\SDK\Alinlp\V20200629\Models\GetSaChGeneralRequest;
use AlibabaCloud\Tea\Exception\TeaUnableRetryError;
use app\v1\image\controller\create;
use app\v1\nlp\model\NlpAliyunModel;
use app\v1\nlp\model\NlpModel;
use Darabonba\OpenApi\Models\Config;
use AlibabaCloud\SDK\Bailian\V20231229\Models\UpdateFileTagRequest;

class index extends create
{

    protected $nlp_proc = [];

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $project = NlpModel::where("project", $this->token)->findOrEmpty();
        if (empty($project)) {
            \Ret::Fail(404, null, "项目不存在");
        } else {
            $this->nlp_proc = $project->toArray();
        }
        switch ($this->nlp_proc["type"]) {
            case "aliyun":
                $this->aliyun();
                break;
        }
    }

    public function index()
    {
        Bai
    }
}