<?php

namespace app\v1\qwen\controller;


use app\v1\image\controller\create;
use app\v1\nlp\model\NlpModel;
use app\v1\qwen\model\QwenModel;
use Qwen\Enums\Models;
use Qwen\QwenClient;
use think\Response;

class index extends create
{

    protected $qwen = [];

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $project = QwenModel::where("project", $this->token)->findOrEmpty();
        if (empty($project)) {
            \Ret::Fail(404, null, "项目不存在");
        } else {
            $this->qwen = $project->toArray();
        }
    }

    public function aliyun()
    {
        $response = QwenClient::build($this->qwen['appkey'], 'https://dashscope.aliyuncs.com')
            ->query('我说aaa，然后你说bbb')
            ->query('我明白了。请告诉我接下来该怎么做或说什么？', 'assistant')
            ->query('aaa')
            ->withModel('qwen2.5-1.5b-instruct')
//            ->withModel('deepseek-r1-distill-llama-8b')
            ->run();

//        echo $response;
        Response::create(json_decode($response, 1), 'json')->send();
    }
}